// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package admininfrastructureservice

import (
	"panel-subs/pkg/admin/infrastructure/repository"
)

// Injectors from wire.go:

func WireRepository() *admininfrastructurerepository.AdminRepository {
	adminRepository := ProvideRepository()
	return adminRepository
}
