// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Insert a product.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "Insert a product.",
                "parameters": [
                    {
                        "description": "Insert Admin Request Parameter",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/panel-subs_pkg_admin_application_request.CreateAdminInfo"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Result",
                        "schema": {
                            "$ref": "#/definitions/panel-subs_pkg_admin_application_response.ApiResponseInsert"
                        }
                    },
                    "400": {
                        "description": "Result",
                        "schema": {
                            "$ref": "#/definitions/panel-subs_pkg_admin_application_response.ApiResponseInsert"
                        }
                    },
                    "422": {
                        "description": "Result",
                        "schema": {
                            "$ref": "#/definitions/panel-subs_pkg_admin_application_response.ApiResponseInsert"
                        }
                    }
                }
            }
        },
        "/health/liveness": {
            "get": {
                "description": "get the liveness status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Show the status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health/readiness": {
            "get": {
                "description": "get the readiness status of server.",
                "consumes": [
                    "*/*"
                ],
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Show the readiness status of server.",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "panel-subs_pkg_admin_application_request.CreateAdminInfo": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "minLength": 8
                }
            }
        },
        "panel-subs_pkg_admin_application_response.ApiResponseInsert": {
            "type": "object",
            "properties": {
                "correlationid": {
                    "type": "string"
                },
                "data": {
                    "$ref": "#/definitions/panel-subs_pkg_admin_application_response.CreateAdminResponse"
                },
                "error": {
                    "type": "string"
                },
                "success": {
                    "type": "boolean"
                },
                "tin": {
                    "type": "string"
                },
                "tout": {
                    "type": "string"
                }
            }
        },
        "panel-subs_pkg_admin_application_response.CreateAdminResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "password": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "PANEL SUB API",
	Description:      "This is Api for province microservice.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
