definitions:
  panel-subs_pkg_admin_application_request.CreateAdminInfo:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 8
        type: string
    required:
    - email
    - name
    - password
    type: object
  panel-subs_pkg_admin_application_response.ApiResponseInsert:
    properties:
      correlationid:
        type: string
      data:
        $ref: '#/definitions/panel-subs_pkg_admin_application_response.CreateAdminResponse'
      error:
        type: string
      success:
        type: boolean
      tin:
        type: string
      tout:
        type: string
    type: object
  panel-subs_pkg_admin_application_response.CreateAdminResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
info:
  contact: {}
  description: This is Api for province microservice.
  termsOfService: http://swagger.io/terms/
  title: PANEL SUB API
  version: "1.0"
paths:
  /admin:
    post:
      consumes:
      - application/json
      description: Insert a product.
      parameters:
      - description: Insert Admin Request Parameter
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/panel-subs_pkg_admin_application_request.CreateAdminInfo'
      produces:
      - application/json
      responses:
        "201":
          description: Result
          schema:
            $ref: '#/definitions/panel-subs_pkg_admin_application_response.ApiResponseInsert'
        "400":
          description: Result
          schema:
            $ref: '#/definitions/panel-subs_pkg_admin_application_response.ApiResponseInsert'
        "422":
          description: Result
          schema:
            $ref: '#/definitions/panel-subs_pkg_admin_application_response.ApiResponseInsert'
      security:
      - Bearer: []
      summary: Insert a product.
      tags:
      - product
  /health/liveness:
    get:
      consumes:
      - '*/*'
      description: get the liveness status of server.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show the status of server.
      tags:
      - Health
  /health/readiness:
    get:
      consumes:
      - '*/*'
      description: get the readiness status of server.
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Show the readiness status of server.
      tags:
      - Health
schemes:
- https
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
